name: "[Test] - Cypress - Admin"

run-name: "${{ github.workflow }}: ${{ github.ref_name }} - ${{ inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: "Qase API URL"
        required: true
      qase_report:
        description: "Enabled/disabled reporting to Qase"
        required: true
      qase_project_code:
        description: "Qase project code"
        required: true
      qase_run_id:
        description: "Qase Run ID"
        required: true
      qase_run_complete:
        description: "Qase Run autocomplete"
        required: true
      environment:
        type: choice
        description: Deployment Environment
        required: true
        default: 'coffee'
        options:
          - coffee
          - fail
          - how
          - lol
          - maison
          - ninja
          - red
          - rip
          - wtf
          - wine
      test:
        description: Select test
        required: true
        type: choice
        default: 'noteTab'
        options:
          - '**'
          - noteTab
          - refundTab
          - reviewTab
          - relatedTab
          - summaryTab
          - transactionsPage
          - userPermissions
      number-of-concurrent-jobs:
        type: string
        default: '[1,2,3]'
  workflow_call:
    inputs:
      qase_api_base_url:
        type: string
      qase_report:
        type: string
      qase_project_code:
        type: string
      qase_run_id:
        type: string
      qase_run_complete:
        type: string
      environment:
        type: string
      test:
        type: string
      number-of-concurrent-jobs:
        type: string
        default: '[1,2,3]'

env:
  QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
  QASE_TESTOPS_PROJECT: ${{ inputs.qase_project_code }}
  QASE_TESTOPS_RUN_ID: ${{ inputs.qase_run_id }}
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
  QASE_TESTOPS_RUN_COMPLETE: true
  QASE_MODE: "testops"

jobs:
  cypress-test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: ${{ fromJson(inputs.number-of-concurrent-jobs) }}
    steps:
      - uses: cskmnrpt/qase-link-run@v2
        env:
          QASE_TESTOPS_API_TOKEN: ${{ env.QASE_TESTOPS_API_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pytest tests
        run: |
          pytest tests/ -v
        env:
          QASE_MODE: "testops"
          QASE_TESTOPS_PROJECT: "QTP"
          QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
          QASE_TESTOPS_RUN_ID: ${{ inputs.qase_run_id }}
          QASE_TESTOPS_RUN_COMPLETE: "true"
          QASE_ENVIRONMENT: ${{ inputs.environment }}
